app = "kartonger"
primary_region = "arn"

[env]
  PORT = "3000"
  RACK_ENV = "production"
  RUBYOPT = "-W:deprecated"

[mounts]
  source = "storage"
  destination = "/storage"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
